---
title: "project_temp_100"
author: "JosephKBS"
date: "10/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


1. Fetching datasets from the files
```{r}
library(ggplot2)
library(ggthemes)
co2emi <- read.csv("./data/annual-co2-emissions-per-country (1).csv")[22851:23019,3:4]
temp_ano <-  read.csv("./data/temperature-anomaly.csv")[1:169,2:3]
 glotemp <-  read.csv("./data/globaltempfrom1880to2019.csv", header = TRUE)[2:141,1:14]
```

2. data cleaning 
```{r}
# change to dataframe
df <- data.frame( rbind(co2emi[,2], temp_ano[,2], temp_ano[,1] ))
# transpose
df <- as.data.frame(t(as.matrix(df)))
# rowname 
rownames(df)<-c()
colnames(df) <- c("co2", "temp_anomaly", "year")
head(df)
```

3. checking the types of data
```{r}
str(df)
```

4. scaling the data (difference in unit of measurement)
```{r}
df_norm <- scale(df[,1:2])
df_norm <- data.frame(  cbind( df_norm, df$year) )
colnames(df_norm) <- c("co2" ,"temp_anomaly", "year")
head(df_norm)
```
5. visualize the data
```{r}
ggplot(df_norm, aes(year))+
  geom_line(aes(y=co2, col="co2 emission") ) + 
  geom_line(aes(y=df_norm$temp_anomaly, col="temp anomaly")) +
  labs(title="Global temperature anomaly and co2 emission", 
    caption="Source: U.S. EPICA, NOAA", x="Years", y="Scaled carbon dioxide emission")+
    theme_economist() 
```

6. Looking at the new data 
```{r}
ggplot(df_norm, aes(x=year, y=temp_anomaly)) + 
        geom_point( color="blue", alpha=0.3, size=2) +
        geom_line(aes(y=co2, col="co2")) +
  labs(title="Carbon Dioxide Emission and global temperature anomlay", 
    subtitle="World wide data", 
    caption="Source: U.S. EPICA",x="Years", y="Amount(scaled)")+
    theme_classic() 
```
To check whether the type of the data.
```{r}
 df_g <- data.frame( glotemp )
str(df_g)
```

adjust the length of data
```{r}
 df_g <- data.frame( glotemp )

df_g_y<- as.numeric(df_g[,1])
df_g_1<- as.numeric(df_g[,2])
df_g_2<- as.numeric(df_g[,3])
df_g_3<- as.numeric(df_g[,4])
df_g_4<- as.numeric(df_g[,5])
df_g_5<- as.numeric(df_g[,6])
df_g_6<- as.numeric(df_g[,7])
df_g_7<- as.numeric(df_g[,8])
df_g_8<- as.numeric(df_g[,9])
df_g_9<- as.numeric(df_g[,10])
df_g_10<- as.numeric(df_g[,11])
df_g_11<- as.numeric(df_g[,12])
df_g_12<- as.numeric(df_g[,13])
df_g_a<- as.numeric(df_g[,14])
```


```{r}
df_g <- data.frame( rbind(df_g_y, df_g_1, df_g_2, df_g_3, df_g_4, df_g_5, df_g_6, df_g_7, df_g_8, df_g_9,df_g_10,df_g_11, df_g_12, df_g_a) )

df_g <- as.data.frame(t(as.matrix(df_g)))
rownames(df_g)<-c()
colnames(df_g) <- c("year","jan","feb","mar","apr","may","june","july","aug","sep","oct","nov","dec","ave")
df_g <- df_g[1:139,]
head(df_g)
str(df_g)
```

```{r}
newdata <- data.frame(matrix(NA, nrow=12*138, ncol=3 ))

new_data[,1] <- cat(df_g[,1], df_g[,1], df_g[,1], df_g[,1], df_g[,1], df_g[,1], df_g[,1], df_g[,1] ,df_g[,1], df_g[,1], df_g[,1], df_g[,1])
new_data[,2] <- cat(df_g[,2], df_g[,3], df_g[,4], df_g[,5], df_g[,6], df_g[,7], df_g[,8], df_g[,9], df_g[,10], df_g[,11], df_g[,12]) 
# new_data[,3] <- 

new_data
```

```{r}
x <-1
repeat{
  print("jan")
  x=x+1
  if(x==139){ break}
}
```

